#
# colors: https://flatuicolors.com/
#
# kind/ - The type of issue
- name: kind/bug
  description: A bug; unintended behavior
  color: 425df5
- name: kind/feature
  description: A feature request; new or enhanced behavior
  color: 425df5
- name: kind/support
  description: Questions, supporting users, etc.
  color: 425df5
- name: kind/documentation
  description: Documentation of enhancd itself
  color: 425df5
- name: kind/deprecation
  description: Related to a feature or part of code being deprecated.
  color: 425df5
- name: kind/cleanup
  description: Categorizes issue or PR as related to cleaning up code, issues, etc.
  color: 425df5
- name: kind/breaking-change
  description: Denotes a PR that introduces potentially breaking changes that require user action.
  color: 425df5

# area/ - The area of work that needs to be executed against
- name: area/bash
  description: Catch all for changes in bash files
  color: cccccc
- name: area/zsh
  description: Catch all for changes in zsh files
  color: cccccc
- name: area/fish
  description: Catch all for changes in fish files
  color: cccccc
- name: area/awk
  description: Catch all for changes in awk files
  color: cccccc

# missing/ - The area of missing files with according to edited files against
- name: missing/bash
  description: Denotes a PR that needs to include changes against missing area
  color: fd79a8
- name: missing/fish
  description: Denotes a PR that needs to include changes against missing area
  color: fd79a8

# triage/ - The state of an issue being triaged
- name: triage/waiting
  description: Needs to be placed into a milestone, or be closed by maintainers
  color: f58442
- name: triage/blocked
  description: Cannot move forward until some roadblock is lifted
  color: f58442
- name: triage/needs-info
  description: An issue that needs more investigation from maintainers or more info from the issue provider
  color: f58442
- name: triage/duplicate
  description: A duplicate issue. These issues are usually closed after receiving this label
  color: f58442

# release/
- name: release/major
  description: Indicates major version to bump up next
  color: 1dd1a1
- name: release/minor
  description: Indicates minor version to bump up next
  color: 1dd1a1
- name: release/patch
  description: Indicates patch version to bump up next
  color: 1dd1a1

# tagpr
- name: tagpr
  description: Used by tagpr for managing the release
  color: ededed
- name: tagpr:minor
  description: Used by tagpr for managing the release
  color: ededed
- name: tagpr:major
  description: Used by tagpr for managing the release
  color: ededed

# lifecycle/ - Where something is at in it's lifecycle
- name: lifecycle/stale
  description: Labeled by GitHub actions after 30 days of inactivity
  color: feca57
- name: lifecycle/rotten
  description: >- # join lines with spaces (>) and remove last newline (-)
    Labeled by GitHub actions after 30 days of having 'lifecycle/stale' label.
    Issues and PRs with this label will close after another 30 days of inactivity.
  color: feca57
- name: lifecycle/frozen
  description: Prevents GitHub actions from labeling Issues and PRs with 'lifecycle/stale' or 'lifecycle/rotten'.
  color: feca57
- name: lifecycle/todo
  description: Denote issues or PRs that the maintainer has determined to be willing to work on
  color: feca57
- name: lifecycle/wont-do
  description: Denote issues or PRs that the maintainer has determined to be willing not to execute against
  color: feca57
